# Generated by Django 5.1.1 on 2024-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='youtube',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
