# Generated by Django 5.1.1 on 2024-10-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_info_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='birthday',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
