# Generated by Django 5.1.1 on 2024-10-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_birthday_alter_info_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='birthday',
        ),
    ]
