# Generated by Django 5.1.1 on 2024-10-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
